### PR TITLE
LeafManager LeafArray bugfix from RootNode<LeafNode>

### LINKED ISSUE #1456: [BUG] LeafManager::initLeafArray fails for "shallow" trees
Issue created to track this comment thread:

https://github.com/AcademySoftwareFoundation/openvdb/commit/ac841ea1051e21b9978f1d5f6d7b732b837459b6#commitcomment-81933648

Essentially if you only have a RootNode->LeafNodes (i.e. no InternalNodes) then the LeafManager fails to cache the LeafNodes

### PR DESCRIPTION
**Pull request by Idclip**
Closes #1456

### CODE REVIEW

File: openvdb/openvdb/tree/LeafManager.h [hunk 1]
```diff
@@ -586,7 +586,12 @@ class LeafManager
         using LeafParentT = typename CopyConstness<TreeType, NonConstLeafParentT>::Type;
 
         std::deque<LeafParentT*> leafParents;
-        mTree->getNodes(leafParents);
+        if constexpr(std::is_same<LeafParentT, RootNodeType>::value) {
+            leafParents.emplace_back(&mTree->root());
+        }
+        else {
+            mTree->getNodes(leafParents);
```
Comment (Idclip) [inline openvdb/openvdb/tree/LeafManager.h:593]: Maybe getNodes should ust do the above if NodeT* of the provided array is the RootNode

**Review by danrbailey — APPROVED** [review]
